name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9
  - nodejs
  - jupyterlab>3
  - numpy>=1.18.1
  - h5py
  - holidays
  - scipy>=1.3.0
  - toolz
  - bokeh>=2.0.0
  - dask=2022.6.1
  - dask-labextension>5
  - distributed=2022.6.1
  - notebook
  - matplotlib
  - Pillow
  - pandas>=1.0.1
  - pandas-datareader
  - pytables
  - scikit-learn>=0.22.1
  - scikit-image>=0.15.0
  - snakeviz
  - ujson
  - pip
  - s3fs
  - fastparquet
  - pyarrow
  - dask-ml
  - ipywidgets>=7.5
  - cachey
  - python-graphviz
  - ipycytoscape
  - zarr
