name: dask-tutorial-22
channels:
  - conda-forge
dependencies:
  - python=3.9
  - nodejs
  - jupyterlab>=2.0.0
  - numpy>=1.18.1
  - h5py
  - holidays
  - scipy>=1.3.0
  - bokeh>=2.0.0
  - dask=2022.06.1
  - dask-labextension
  - distributed=2022.06.1
  - notebook
  - matplotlib
  - pandas>=1.0.1
  - pytables
  - scikit-learn>=0.22.1
  - pip
  - s3fs
  - pyarrow
  - ipywidgets>=7.5
  - python-graphviz
  - ipycytoscape
  - zarr
  - ipycytoscape
  - pooch
  - xarray
  - jupyter_bokeh
  - mamba
  - ipywidgets
